-- V1 baseline: current schema (matches Hibernate default naming as of Phase 6:
-- SpringPhysicalNamingStrategy: camelCase -> snake_case, NO pluralization.
-- users is explicit via @Table on the User entity; sprint/task use defaults.)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    role VARCHAR(255) NOT NULL,
    github_username VARCHAR(255),
    daily_capacity_hours INTEGER NOT NULL
);

CREATE TABLE sprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE,
    end_date DATE
);

CREATE TABLE task (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255),
    estimated_hours INTEGER NOT NULL,
    status VARCHAR(255),
    user_id BIGINT,
    sprint_id BIGINT,
    CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_task_sprint FOREIGN KEY (sprint_id) REFERENCES sprint (id)
);

CREATE INDEX idx_task_user ON task (user_id);
CREATE INDEX idx_task_sprint ON task (sprint_id);
