-- V5: GitHub sync depth + team settings extension (Phase 11).
-- task: issue metadata captured during sync (manual tasks keep NULLs)
ALTER TABLE task ADD COLUMN issue_url VARCHAR(512);
ALTER TABLE task ADD COLUMN github_closed_at TIMESTAMP;

-- synced_repository: every repo ever synced successfully; the scheduled
-- auto-sync job re-syncs these (Phase 11).
CREATE TABLE synced_repository (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    repo VARCHAR(255) NOT NULL,
    last_synced_at TIMESTAMP,
    last_result VARCHAR(255),
    last_status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_synced_repository UNIQUE (owner, repo)
);

-- team_settings: sync frequency + capacity alert toggles (Phase 11)
ALTER TABLE team_settings ADD COLUMN sync_frequency VARCHAR(16) NOT NULL DEFAULT 'manual';
ALTER TABLE team_settings ADD COLUMN capacity_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE team_settings ADD COLUMN underallocation_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE;
