-- V6: sprint burndown snapshots (Phase 11).
-- One row per sprint per day while the sprint is active; written by the
-- scheduled snapshot job. This is what makes the burndown chart real history
-- rather than an invented line.
CREATE TABLE sprint_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sprint_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    remaining_hours INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_snapshot_sprint FOREIGN KEY (sprint_id) REFERENCES sprint (id),
    CONSTRAINT uk_snapshot_sprint_date UNIQUE (sprint_id, snapshot_date)
);
CREATE INDEX idx_snapshot_sprint ON sprint_snapshot (sprint_id);
